export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS", // sidebar playlists
  SET_USER: "SET_USER",
  SET_PLAYLIST_SONGS: "SET_PLAYLIST_SONGS",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
};
